# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded VolArea 1.0 [list source [file join $dir main.tcl]]
package ifneeded GUI 1.0	[list source [file join $dir/Routines/Lib Gui.tcl]]
package ifneeded Box_Proc 1.0   [list source [file join $dir/Routines/Lib Box_Proc.tcl]]
package ifneeded SASA_Proc 1.0  [list source [file join $dir/Routines/Lib SASA_Proc.tcl]]
package ifneeded SQL 1.0 	[list source [file join $dir/Routines/Lib sqlite_man.tcl]]
package ifneeded vdw 1.0 	[list source [file join $dir/Routines/Lib Vdw_func.tcl]]
package ifneeded out 1.0 	[list source [file join $dir/Routines/Lib output.tcl]]
package ifneeded graph 1.0 	[list source [file join $dir/Routines/Lib makegraph.tcl]]
package ifneeded vol 1.0 	[list source [file join $dir/Routines/Lib vol.tcl]]
package ifneeded view_points 1.0 [list source [file join $dir/Routines/Lib view_points.tcl]]
package ifneeded image 1.0 	[list source [file join $dir/Routines/Lib image.tcl]]
package ifneeded cmdline 1.3.1 [list source [file join $dir/Routines/Other/graph/cmdline cmdline.tcl]]
package ifneeded xyplot 1.0.0 [list source [file join $dir/Routines/Other/graph/editgraph xyplot.tcl]]
package ifneeded editgraph 1.0 [list source [file join $dir/Routines/Other/graph/editgraph editgraph.tcl]]
package ifneeded Plotchart 1.8 [list source [file join $dir/Routines/Other/graph/plotchart plotchart.tcl]]

if {![package vsatisfies [package provide Tcl] 8.2]} {return}
package ifneeded math 1.2.4 [list source [file join $dir/Routines/Other/math math.tcl]]


if {![package vsatisfies [package provide Tcl] 8.4]} {return}
# statistics depends on linearalgebra (for multi-variate linear regression).
package ifneeded math::statistics 0.6 [list source [file join $dir/Routines/Other/math statistics.tcl]]
